17:57:09 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 12: 'trans'. Did you forget to register or load this tag?"), <traceback object at 0x0000015FD65F3CC0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 178, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'trans'. Did you forget to register or load this tag?
17:57:09 : ERROR : "GET /news/index/ HTTP/1.1" 500 151331 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
18:00:36 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 12: 'trans'. Did you forget to register or load this tag?"), <traceback object at 0x000001E7BA1A4A40>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 178, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'trans'. Did you forget to register or load this tag?
18:00:36 : ERROR : "GET /news/index/ HTTP/1.1" 500 151512 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
18:35:48 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x000001C3CB5F6EC0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 179, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
18:35:48 : ERROR : "GET /news/index/ HTTP/1.1" 500 136945 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
10:54:09 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x00000148FD602C40>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 179, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
10:54:10 : ERROR : "GET /news/index/ HTTP/1.1" 500 136808 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
10:54:44 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x00000148FD6B0F80>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 179, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
10:54:44 : ERROR : "GET /news/index/ HTTP/1.1" 500 136808 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
10:56:32 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name."), <traceback object at 0x00000148FD6011C0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 179, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'set_language' not found. 'set_language' is not a valid view function or pattern name.
10:56:32 : ERROR : "GET /news/index/ HTTP/1.1" 500 136808 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:25:24 : ERROR : Internal Server Error: /admin/news/post/92/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000024710E4A440>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1767, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 866, in get_object
    return queryset.get(**{field.name: object_id})
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:25:24 : ERROR : "GET /admin/news/post/92/change/ HTTP/1.1" 500 188126 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:25:43 : ERROR : Internal Server Error: /admin/news/post/92/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000024710D2CB00>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1767, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 866, in get_object
    return queryset.get(**{field.name: object_id})
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:25:43 : ERROR : "GET /admin/news/post/92/change/ HTTP/1.1" 500 188126 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:25:52 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000024710DDC4C0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 181, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaulttags.py", line 194, in render
    len_values = len(values)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:25:52 : ERROR : "GET /news/index/ HTTP/1.1" 500 189939 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:26:16 : ERROR : Internal Server Error: /news/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000024710E9B740>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaultfilters.py", line 609, in length
    return len(value)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:26:16 : ERROR : "GET /news/ HTTP/1.1" 500 239372 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:27:34 : ERROR : Internal Server Error: /news/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000027DB1D83C80>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\templatetags\cache.py", line 53, in render
    value = self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 742, in resolve
    new_obj = func(obj, *arg_vals)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\defaultfilters.py", line 609, in length
    return len(value)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:27:34 : ERROR : "GET /news/ HTTP/1.1" 500 239372 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:27:49 : ERROR : Internal Server Error: /admin/news/post/92/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.post_author_en_us_id'), <traceback object at 0x0000027DB1C49EC0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: news_post.post_author_en_us_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1767, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 866, in get_object
    return queryset.get(**{field.name: object_id})
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such column: news_post.post_author_en_us_id
13:27:49 : ERROR : "GET /admin/news/post/92/change/ HTTP/1.1" 500 188126 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:31:56 : ERROR : Internal Server Error: /admin/news/post/92/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x0000021ED3B34CC0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1781, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 300, in __new__
    fields = fields_for_model(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 229, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
AttributeError: 'NoneType' object has no attribute 'required'
13:31:56 : ERROR : "GET /admin/news/post/92/change/ HTTP/1.1" 500 171181 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:33:09 : ERROR : Internal Server Error: /admin/news/post/111/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x0000021ED3EA5900>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1781, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 300, in __new__
    fields = fields_for_model(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 229, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
AttributeError: 'NoneType' object has no attribute 'required'
13:33:09 : ERROR : "GET /admin/news/post/111/change/ HTTP/1.1" 500 170494 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:35:56 : ERROR : Internal Server Error: /admin/news/post/111/change/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x0000021ED3EAE5C0>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 1781, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 300, in __new__
    fields = fields_for_model(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\forms\models.py", line 229, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
AttributeError: 'NoneType' object has no attribute 'required'
13:35:56 : ERROR : "GET /admin/news/post/111/change/ HTTP/1.1" 500 170494 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
15:02:42 : ERROR : Internal Server Error: /news/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 39: 'get_current_language', expected 'endcache'. Did you forget to register or load this tag?"), <traceback object at 0x00000242F1550A40>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\templatetags\cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 39: 'get_current_language', expected 'endcache'. Did you forget to register or load this tag?
15:02:42 : ERROR : "GET /news/ HTTP/1.1" 500 248199 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
