12:48:45 : ERROR : Internal Server Error: /news/index/ : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 13: 'else'. Did you forget to register or load this tag?"), <traceback object at 0x000001E38B036A40>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 229, in get
    return HttpResponse(render(request,
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'else'. Did you forget to register or load this tag?
12:48:45 : ERROR : "GET /news/index/ HTTP/1.1" 500 201686 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:05:19 : ERROR : Internal Server Error: /news/111 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'one_news' not found. 'one_news' is not a valid view function or pattern name."), <traceback object at 0x000001C847520E40>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 114, in post
    return redirect('one_news', pk=self.kwargs['pk'])
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'one_news' not found. 'one_news' is not a valid view function or pattern name.
13:05:19 : ERROR : "POST /news/111 HTTP/1.1" 500 103892 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
13:12:30 : ERROR : Internal Server Error: /news/111 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\utils\log.py : (<class 'django.urls.exceptions.NoReverseMatch'>, NoReverseMatch("Reverse for 'post_detail' with no arguments not found. 1 pattern(s) tried: ['news/(?P<pk>[0-9]+)\\\\Z']"), <traceback object at 0x0000012C0DA4A100>)
Traceback (most recent call last):
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\news_portal\news\views.py", line 114, in post
    return redirect('post_detail')
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_detail' with no arguments not found. 1 pattern(s) tried: ['news/(?P<pk>[0-9]+)\\Z']
13:12:30 : ERROR : "POST /news/111 HTTP/1.1" 500 105452 : C:\Users\feron\Kurss_Django\venv\lib\site-packages\django\core\servers\basehttp.py : None
